name: "actionlint"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  merge_group:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@v8
      with:
        diagnostic-endpoint: ""
    - name: "actionlint"
      run: nix run -Lv --refresh --inputs-from .# nixpkgs#actionlint -- --ignore SC2002
