name: "editor-config"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  editor-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: "install editorconfig-checker"
      run: nix shell --refresh --inputs-from .# nixpkgs#editorconfig-checker
    - name: Checking EditorConfig
      run: |
        cat "$HOME/changed_files" | xargs -r editorconfig-checker -disable-indent-size
    - if: ${{ failure() }}
      run: |
        printf "::error :: Hey! It looks like your changes don't follow our editorconfig settings.\nRead https://editorconfig.org/#download to configure your editor so you never see this error again."
